Adds support for Dispute Scheme Files API (CS1/CS2)
checkout/checkout-sdk-go pull request #26
Opened 2022-12-06 12:24 UTC by martinseco

2022-12-08 12:53 UTC, Armando-Ibarra requested changes

2022-12-08 12:53 UTC, Armando-Ibarra commented on disputes/client.go
> +func (c *Client) GetDisputeSchemeFiles(disputeId string) (*SchemeFilesResponse, error) {
Isn't the test client missing?

2022-12-13 06:27 UTC, armandojaleo commented
LGTM 👍

2022-12-13 14:39 UTC, Armando-Ibarra approved these changes

2022-12-14 14:19 UTC, merged